---
# Handlers for SSH user management role

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
  listen: restart sshd
